;;; package --- Popwin config
;;; Commentary:
;;; Code:
;;popwin-mode===================================================================
(require-package 'popwin)	            					;; 在当前buffer弹出*help*等buffer并能用C-g关闭，很实用
(require 'popwin)
(popwin-mode t)

(setq display-buffer-function 'popwin:display-buffer)
(setq popwin:special-display-config
      '(("*Help*"  :height 30 :stick t)
	("*Completions*" :noselect t)
	("*compilation*" :noselect t)
	("*Backtrace*" :height 30)
	("*Messages*" :height 30)
	("*Occur*" :noselect t)
	("\\*Slime Description.*" :noselect t :regexp t :height 30)
	("*magit-commit*" :noselect t :height 40 :width 80)
	("*magit-diff*" :noselect t :height 40 :width 80)
	("*magit-edit-log*" :noselect t :height 15 :width 80)
	("\\*Slime Inspector.*" :regexp t :height 30)
	("*Ido Completions*" :noselect t :height 30)
	("*eshell*" :height 30)
	("\\*ansi-term\\*.*" :regexp t :height 30)
	("*shell*" :height 30)
	(".*overtone.log" :regexp t :height 30)
	("*gists*" :height 30)
	("*sldb.*":regexp t :height 30)
	("*nrepl-error*" :height 30)
	("*nREPL doc*" :height 30)
	("*Kill Ring*" :height 30)
	("*cscope*" :height 30)
	;; ("*ggtags-global*" :height 30)
	("*xmsi math symbol input*" :height 30)
	("*Google Translate*" :height 30)
	;; ("*multifile*" :noselect :height 30)
	;; ("*Pp Eval Output*" :noselect 30)
	("*Compile-Log*" :height 30)))

(defun show-messages-popwin ()
  (interactive)
  (popwin:display-buffer "*Messages*"))
(defun show-scratch-popwin ()
  (interactive)
  (popwin:display-buffer "*scratch*"))
(defun show-eshell-popwin ()
  (interactive)
  (eshell)
  (popwin:display-buffer "*eshell*"))
(global-set-key (kbd "C-c s m") 'show-messages-popwin)
(global-set-key (kbd "C-c s s") 'show-scratch-popwin)
(global-set-key (kbd "<f5>") 'show-eshell-popwin)
(provide 'popwin-extend)
;;; popwin-extend.el ends here
